---
title: "sampled_5000"
output: html_document
---

```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)

# Get the system information
sys_info <- Sys.info()

# Check the OS and perform actions based on it
if (grepl("Linux", sys_info["sysname"])) {
  cao <- readRDS('../../../data/gene_count_sampled.RDS')
  cell_annotations <- readRDS("../../../data/gene_count_sampled.RDS")
  gene_annotations <- readRDS("../../../data/gene_count_sampled.RDS")
} else if (sys_info["sysname"] == "Windows") {
  cao <- readRDS('C:/Users/hostp/Desktop/data/gene_count_sampled.RDS')
  cell_annotations <- readRDS("C:/Users/hostp/Desktop/data/df_cell.RDS")
  gene_annotations <- readRDS("C:/Users/hostp/Desktop/data/df_gene.RDS")
}


cao <- CreateSeuratObject(counts = cao)

# Ensure the cell names in Seurat object and the sample names in cell_annotations match
common_samples <- intersect(cell_annotations$sample, colnames(cao))

# Subset the cell_annotations data to only include rows with common samples
common_annotations <- cell_annotations[cell_annotations$sample %in% common_samples, ]

# Select specific columns from cell_annotations (e.g., "sample", "cell_type", "treatment")
columns_to_add <- common_annotations[, c("sample", "Organ", "Main_cluster_name", "Organ_cell_lineage")]  # Replace with your column names

# Ensure that the order of rows in `columns_to_add` matches the order of cells in Seurat object
columns_to_add <- columns_to_add[match(common_samples, colnames(cao)), ]

# Add all columns from common_annotations to Seurat object's metadata
cao <- AddMetaData(cao, metadata = columns_to_add)


# Check the updated metadata to confirm the annotations were added
head(cao@meta.data)

```

#### Add Gene_ids

```{r}
# Match gene annotations with rownames in Seurat object (gene names)
matched_genes <- match(rownames(cao), gene_annotations$gene_id)

# Extract the corresponding gene annotations (gene_type and gene_short_name)
gene_metadata <- gene_annotations[matched_genes, c("gene_short_name", "gene_type")]


# Check if any gene annotations did not match
#sum(is.na(gene_metadata$gene_type))

# Add gene metadata as features metadata in the Seurat object
cao[["RNA"]] <- AddMetaData(cao[["RNA"]], metadata = gene_metadata)


# Remove version numbers from gene IDs
rownames(gene_annotations) <- sub("\\..*", "", gene_annotations$gene_id)
rownames(cao[["RNA"]]) <- sub("\\..*", "", rownames(cao[["RNA"]]))

cao@assays[['RNA']]@layers$counts@Dimnames[[1]] <- gene_annotations[["gene_short_name"]]
cao@assays[['RNA']]@layers$counts@Dimnames[[2]] <- gene_annotations$gene_type

```



#### Making subample and performing integration analysis

```{r}
# Subsample 1000 cells randomly
cao_subsample <- subset(cao, cells = sample(Cells(cao), 10000))


# Run standard analysis workflow with suppressed output
suppressMessages({
  suppressWarnings({
    cao_subsample <- NormalizeData(cao_subsample)
    cao_subsample <- FindVariableFeatures(cao_subsample)
    cao_subsample <- ScaleData(cao_subsample)
    cao_subsample <- RunPCA(cao_subsample)
  })
})
```

```{r}
cao_subsample <- FindNeighbors(cao_subsample, dims = 1:30, reduction = "pca")
cao_subsample <- FindClusters(cao_subsample, resolution = 2, cluster.name = "unintegrated_clusters")
```

```{r fig-width=10, fig-height=10, out.width='100%'}

cao_subsample <- RunUMAP(cao_subsample, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
p1 <- DimPlot(cao_subsample, reduction = "umap.unintegrated", group.by = "seurat_clusters") 
p2 <- DimPlot(cao_subsample, reduction = "umap.unintegrated", group.by = "Organ") 
p3 <- DimPlot(cao_subsample, reduction = "umap.unintegrated", group.by = "Main_cluster_name") 

# Arrange plots vertically
final_plot <- p1 / p2 / p3  # `/` stacks them vertically
ggsave("../plots/basic_analysis_workflow.jpg", plot = final_plot, width = 40, height = 40, dpi = 300)
```




```{r}
cao_subsample <- FindVariableFeatures(cao_subsample, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(cao_subsample), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(cao_subsample)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```





### Do it on the full dataset


