---
title: "BPcells"
author: "Gustav Helms (qbg413)"
date: "2025-05-15"
output: html_document
---
```{r}
library(BPCells)
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
```



```{r}
# DONT RUN - REQUIRES DOWNLOADED .h5ad FILE. CREATES METADATA

library(hdf5r)

# Decoder function for categorical variables 
decode_obs_column <- function(h5, column_name) {
  idx <- h5[[paste0("obs/", column_name)]]$read()
  labels <- h5[[paste0("obs/__categories/", column_name)]]$read()
  labels[idx + 1]
}

# Open the h5ad file
h5 <- H5File$new("data_tabula_sapiens/TabulaSapiens.h5ad", mode = "r")

# List available groups - ONLY if you wanna find variable names. 
#h5$ls(recursive = TRUE)

cell_type <- decode_obs_column(h5, "cell_ontology_class")
organ <- decode_obs_column(h5, "organ_tissue")
method <- decode_obs_column(h5, "method")

# Combine with cell IDs
cell_id <- h5[["obs/cell_id"]]$read()

# Clean up
h5$close_all()

# Make final data frame
obs_df <- data.frame(
  cell_id = cell_id,
  cell_type = cell_type,
  organ = organ,
  method = method,
  stringsAsFactors = FALSE
)

# Save metadata to CSV
saveRDS(obs_df, file = "data_tabula_sapiens/TabulaSapiens_bp/tabula_obs_metadata.rds")

```


```{r}
# DONT RUN - REQUIRES .h5ad FILE. CREATES INDEXING OF EXPRESSION MATRIX

# Write the .h5ad file as bp. 
tabula.data <- open_matrix_anndata_hdf5("data_tabula_sapiens/TabulaSapiens.h5ad")
   write_matrix_dir(
     mat = tabula.data,
     dir = 'data_tabula_sapiens/TabulaSapiens_bp'
   )
```


```{r}
# Now that we have the matrix on disk, we can load it
counts_mat <- open_matrix_dir(dir = "data_tabula_sapiens/TabulaSapiens_bp")

# Read metadata 
obs_df <- readRDS("data_tabula_sapiens/TabulaSapiens_bp/tabula_obs_metadata.rds")

# Create Seurat Object
tabula <- CreateSeuratObject(counts = counts_mat, meta.data = obs_df)

# Subset only one method
tabula <- subset(tabula, method %in% "10X")

# Remove method col
tabula$method <- NULL
```


```{r}
###### PREPROCESSING #######

# Compute mitochondrial pt
tabula[["percent.mt"]] <- PercentageFeatureSet(tabula, pattern = "^MT-")

# View features
VlnPlot(tabula, c("nCount_RNA", "nFeature_RNA", "percent.mt"))

# Filter out features below 7500 and 5 percent_mt - REMOVING 4603 cells
tabula <- subset(tabula, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 5)
```


```{r}
# Normalize the data
tabula <- NormalizeData(tabula, normalization.method = "LogNormalize")

# Remove redudant cols and save seurat obj
tabula@meta.data <- tabula@meta.data %>% 
  mutate(
    orig.ident = NULL,
    cell_id = NULL,
    percent.mt = NULL
  )

# Save as .rds
saveRDS(tabula, "data_tabula_sapiens/tabula_preproccesed.rds")
```







